### ISSUE TITLE
MetaGeneMark configuration issues

### ISSUE THREAD

**Issue by Buserj** [s0sat/MPASS#1]
Hello,

I'm looking to use `MPASS.pl` on deinterleaved fastq reads.  I've been working to configure MetaGeneMark and create a path, but I'm really stuck.  I have [downloaded from Github ](https://github.com/aghozlane/spasm/tree/master/MetaGeneMark/mgm) using "raw" and `wget` to acquire `gm_key`, `gmhmmp2`, and `MetaGeneMark_v1.mod` and established a path for gm_key using `cp gm_key ~/.gm_key`. I have all files in the same directory as my deinterleaved reads (n = 3 unique samples, 6 total .fastq files) and the `MPASS.pl` script.  After running `perl MPASS.pl -d DISTANCElist.txt -o MPASSmatrix.txt -e 10 -t 8` I am continually receiving the error `Error: Softwares or config files are not installed.` I have ensured all other dependencies (`seqtk`, `spades`, and `blast-legacy`) are properly installed.  

I have also tried the same process using the [MetaGeneMark source](http://topaz.gatech.edu/genemark/license_download.cgi) you provided, specifying my computer's software and OS.  This yielded a new key file and a folder including `gmhmmp2`, `compp`, `biogem`, `gms2.pl`, several `*.mod` files and install/license information.  I established the key path using `cp`, and moved all files and scripts to my pwd with `MPASS.pl` and my reads.  I still received the same error.  

I apologize if this is a simple error, or outside your wheelhouse.  I'm excited to use MPASS!

Thank you,
Jessica

**Comment by s0sat** [comment]
Thank you for using the MPASS.

MPASS.pl is designed to use MetaGeneMark (gmhmmp). Unfortunately, it is not possible to use MetaGeneMark-2 (gmhmmp2). The error message displayed when running MPASS.pl (Error: Softwares or config files are not installed.) occurred because the path to gmhmmp could not be verified. Installing MetaGeneMark and creating the path will solve this problem.

MetaGeneMark can be downloaded from the following URLs:
1. http://exon.gatech.edu/license_download.cgi
2. https://github.com/aghozlane/spasm/tree/master/MetaGeneMark.

**Comment by Buserj** [comment]
Ah, thank you so much.  I was hoping it'd be something simple like that.  For others who may read this:

my pwd has MPASS.pl, my forward and reverse fastq files, MetaGeneMark_v1.mod, gmhmmp* and established a path for gm_key using cp gm_key ~/.gm_key.

I'm excited for the results!

**Comment by Buserj** [comment]
Thank you so much!  I'm really appreciative of your help.

I apologize in advance, but I have a new question.  The script runs but is returning an error regarding metaSPAdes.  

```
cp: cannot stat ‘contigs.fasta’: No such file or directory
cp: cannot stat ‘contigs.fasta’: No such file or directory
cp: cannot stat ‘contigs.fasta’: No such file or directory
mv: cannot stat ‘*_aa’: No such file or directory
        Full Command:                      perl MPASS.pl d MPASSfulllist.txt -o MPASSfulldist.txt -e 10 -t 8 
        Memory (kb):                       18309536 
        # SWAP  (freq):                    0 
        # Waits (freq):                    2451 
        CPU (percent):                     99% 
        Time (seconds):                    86.43 
        Time (hh:mm:ss.ms):                1:26.43 
        System CPU Time (seconds):         17.24 
        User   CPU Time (seconds):         68.78 
```

I have never used perl before so I'm a little lost because `contigs.fasta` is an output folder.  I tried specifying this output in my command, and I've created the folder manually but with the same results.  Same concern with the *_aa file (isn't that the input to blast-legacy?) 

Thank you so much; I'm really excited to see the output for my study system.

**Comment by s0sat** [comment]
Thank you for your question.

In this step of the MPASS pipeline, after running metaSPAdes, contigs.fasta is moved to another folder (copied from the metaSPAdes-output folder to the MPASStmp_GPD folder) and then used for MetaGeneMark. Perhaps the error message is because metaSPAdes did not run (or crashed), and contigs.fasta was not created.

Since metaSPAdes requires a large amount of memory, contigs.fasta cannot be generated if the input fastq file is too large. Additionally, MPASS performs random sampling of reads for all fastq files using seqtk before running metaSPAdes, and the number of reads sampled at this stage should match the number of reads in the fastq file with the smallest file size used for MPASS. Consequently, using smaller fastq files may provide a solution.

I suggest that you initially attempt to run metaSPAdes using the smallest file size of the paired-fastq files you plan to analyze. If metaSPAdes terminates due to insufficient memory, you can potentially resolve this issue by reducing the number of reads using seqtk before using MPASS. When running MPASS, if you reduce the number of reads in any paired fastq files, the other fastq files will be downsampled to match that number of reads.
